---
- include_tasks: packages.yml

# Dev use only
- include_tasks: module_pr.yml
  when: foreman_installer_module_prs is defined

- include_tasks: facts.yml

- include_tasks: installer.yml

- include_tasks: upgrade.yml
  when: foreman_installer_upgrade == True

- include_tasks: ha-extras.yml
  tags:
    - ha_extras
